[project]
name = "hello-world"
version = "0.1.0"
requires-python = ">=3.15.0b2"
dependencies = []

[tool.kivy]
display_name = "Hello World"
app_dir = "src"
entry_point = "main"
orientation = ["portrait"]

[tool.kivy.ios]
schema_version = 1
bundle_id = "org.example.hello-world"  # TODO: change to your reverse-DNS bundle identifier
build = 1
deployment_target = "13.0"

[tool.kivy.ios.python]
version = "3.15.0b2"

[tool.kivy.ios.signing]
team_id = ""
identity = "Apple Development"
provisioning_profile = ""
auto_signing = true
upload_symbols = true
