/*
 * kivy-ios generated entry point.
 *
 * All SDL and CPython bootstrap logic lives in kivy_ios_bootstrap.m so that
 * this file stays stable across Kivy dependency updates.  Per-project values
 * (entry module, app directory, Python version) are supplied by
 * main_config.h, which is regenerated by `toolchain build` whenever project
 * settings change.
 */
#include "kivy_ios_bootstrap.h"
#include "main_config.h"

int main(int argc, char *argv[]) {
    return kivy_ios_main(argc, argv, ENTRY_POINT, APP_DIR, PYTHON_MAJOR_MINOR);
}
